compile-and-run::
	@g++ bubble_sort.cpp \
		heap_sort.cpp \
		insertion_sort.cpp \
		merge_sort.cpp \
		quick_sort.cpp \
		select_sort.cpp \
		stooge_sort.cpp \
		data_reader.cpp \
		main.cpp \
		-o app.out && ./app.out

run::
	@./app.out